config/routes.rb
Rails.application.routes.draw do
  
  get '', to: 'home#home', as: 'root'

  get 'unauthorized', to: 'home#unautorized'

  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    # registrations: 'users/registrations'
  }

  # namespace :user do
  #   root :to => "users#index"
  # end
  
  namespace :admin do
    # get 'users', to: 'users#index'
    # get 'users/new', to: 'users#new'
    # post 'users', to: 'users#create'
    # get 'users/:id', to: 'users#show', as: 'users_detail'
    resources :users
    resources :places
    resources :associateds

    get 'binnacle/list'
  end

  # resources :associated_place_referrals
  # resources :place_associateds
  resources :referrals
  resources :referreds
  # resources :associateds

  get ':id_referred/referrals', to: 'referrals#referrals_active', as: 'referrals_scanned'
  post ':id_referred/referrals', to: 'referrals#add_comment', as: 'referral_add_comment'
  # post 'add_comment', to: 'referrals#add_comment', as: 'referral_add_comment'
  get 'scan_qr', to: 'referrals#scan_qr', as: 'scan_referrals'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/place_associated.rb
class PlaceAssociated < ApplicationRecord
  belongs_to :place
  belongs_to :associated

  validates :associated, uniqueness: { scope: :place }
end

app/controllers/place_associateds_controller.rb
class PlaceAssociatedsController < ApplicationController
  load_and_authorize_resource
  before_action :set_place_associated, only: [:show, :edit, :update, :destroy]

  # GET /place_associateds
  # GET /place_associateds.json
  def index
    @place_associateds = PlaceAssociated.all
  end

  # GET /place_associateds/1
  # GET /place_associateds/1.json
  def show
  end

  # GET /place_associateds/new
  def new
    @place_associated = PlaceAssociated.new
  end

  # GET /place_associateds/1/edit
  def edit
  end

  # POST /place_associateds
  # POST /place_associateds.json
  def create
    @place_associated = PlaceAssociated.new(place_associated_params)

    respond_to do |format|
      if @place_associated.save
        format.html { redirect_to @place_associated, notice: 'Place associated was successfully created.' }
        format.json { render :show, status: :created, location: @place_associated }
      else
        format.html { render :new }
        format.json { render json: @place_associated.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /place_associateds/1
  # PATCH/PUT /place_associateds/1.json
  def update
    respond_to do |format|
      if @place_associated.update(place_associated_params)
        format.html { redirect_to @place_associated, notice: 'Place associated was successfully updated.' }
        format.json { render :show, status: :ok, location: @place_associated }
      else
        format.html { render :edit }
        format.json { render json: @place_associated.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /place_associateds/1
  # DELETE /place_associateds/1.json
  def destroy
    @place_associated.destroy
    respond_to do |format|
      format.html { redirect_to place_associateds_url, notice: 'Place associated was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place_associated
      @place_associated = PlaceAssociated.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_associated_params
      params.require(:place_associated).permit(:place_id, :associated_id)
    end
end

app/helpers/place_associateds_helper.rb
module PlaceAssociatedsHelper
end

app/views/place_associateds/_form.html.erb
<%= form_with(model: place_associated, local: true) do |form| %>
  <% if place_associated.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place_associated.errors.count, "error") %> prohibited this place_associated from being saved:</h2>

      <ul>
      <% place_associated.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :place_id %>
    <%= form.text_field :place_id %>
  </div>

  <div class="field">
    <%= form.label :associated_id %>
    <%= form.text_field :associated_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/place_associateds/edit.html.erb
<h1>Editing Place Associated</h1>

<%= render 'form', place_associated: @place_associated %>

<%= link_to 'Show', @place_associated %> |
<%= link_to 'Back', place_associateds_path %>

app/views/place_associateds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Place Associateds</h1>

<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Associated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @place_associateds.each do |place_associated| %>
      <tr>
        <td><%= place_associated.place %></td>
        <td><%= place_associated.associated %></td>
        <td><%= link_to 'Show', place_associated %></td>
        <td><%= link_to 'Edit', edit_place_associated_path(place_associated) %></td>
        <td><%= link_to 'Destroy', place_associated, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place Associated', new_place_associated_path %>

app/views/place_associateds/new.html.erb
<h1>New Place Associated</h1>

<%= render 'form', place_associated: @place_associated %>

<%= link_to 'Back', place_associateds_path %>

app/views/place_associateds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Place:</strong>
  <%= @place_associated.place %>
</p>

<p>
  <strong>Associated:</strong>
  <%= @place_associated.associated %>
</p>

<%= link_to 'Edit', edit_place_associated_path(@place_associated) %> |
<%= link_to 'Back', place_associateds_path %>