config/routes.rb
Rails.application.routes.draw do
  
  get '', to: 'home#home', as: 'root'

  get 'unauthorized', to: 'home#unautorized'

  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    # registrations: 'users/registrations'
  }

  # namespace :user do
  #   root :to => "users#index"
  # end
  
  namespace :admin do
    # get 'users', to: 'users#index'
    # get 'users/new', to: 'users#new'
    # post 'users', to: 'users#create'
    # get 'users/:id', to: 'users#show', as: 'users_detail'
    resources :users
    resources :places
    resources :associateds

    get 'binnacle/list'
  end

  # resources :associated_place_referrals
  # resources :place_associateds
  resources :referrals
  resources :referreds
  # resources :associateds

  get ':id_referred/referrals', to: 'referrals#referrals_active', as: 'referrals_scanned'
  post ':id_referred/referrals', to: 'referrals#add_comment', as: 'referral_add_comment'
  # post 'add_comment', to: 'referrals#add_comment', as: 'referral_add_comment'
  get 'scan_qr', to: 'referrals#scan_qr', as: 'scan_referrals'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord

    validates :name, presence: true, length: { maximum: 50 }

end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < ApplicationController
  load_and_authorize_resource
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save

        Binnacle.create_binnacle('Crear área', current_user, nil, 
          nil, nil, nil, 
          nil, nil, @place.name, nil, nil)
        format.html { redirect_to edit_admin_place_url(@place), notice: 'El área se creó correctamente.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)

        Binnacle.create_binnacle('Editar área', current_user, nil, 
          nil, nil, nil, 
          nil, nil, @place.name, nil, nil)
        format.html { redirect_to edit_admin_place_url(@place), notice: 'El área se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    begin
      name = @place.name
      @place.destroy
      respond_to do |format|

        Binnacle.create_binnacle('Borrar área', current_user, nil, 
          nil, nil, nil, 
          nil, nil, name, nil, nil)

        format.html { redirect_to admin_places_url, notice: 'El área fue destruido con éxito.' }
        format.json { head :no_content }
      end
    rescue ActiveRecord::InvalidForeignKey
      msg = 'El area "'+@place.name+'" esta asignada a un asociado o referimiento, no puede ser eliminado.'
      respond_to do |format|
        format.html { redirect_to admin_places_url, alert: msg }
        format.json { head :no_content }
      end
    end
      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/admin/places/_form.html.erb
<%= simple_form_for([:admin, place], html: {multipart: true}, :defaults => { :input_html => { :class => "form-control" } }) do |f| %>

  <%= render  :partial=>"shared/display_errors", :locals => {:resource => @place, :field => ''} %>

  <div class="form-group col-sm-12 <%= "has-error" if @place.errors[:name].any? %>">
    <%= f.label :name, class: 'control-label' %>
    <%= f.input_field :name %>
    <%= f.error :name, class:'help-block' %>
  </div>


	<div class="form-group col-sm-12 " style="margin-bottom: 4px;" >
		
		<%= f.submit 'Guardar', :class => 'button right' %>
		
    <%= link_to 'Atrás', admin_places_path, class: 'dark left' %>
			
	</div>
<% end %>

app/views/admin/places/edit.html.erb
<% content_for :title do %>
    Editar área
<% end %>

<div class="container-fluid">
    <div class="row">


        <div class="content-form col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
            <h3 class="col-sm-12 page-title" >EDITAR ÁREA</h3>            
            <%= render 'form', place: @place %>
        </div>

    </div>
</div>

app/views/admin/places/index.html.erb
<% content_for :title do %>
    Áreas
<% end %>


<div class="container-fluid">
  <div class="row">

    <div class="content-index-title" >
      <h3 class ="index-title"></h3> 
      <%= link_to 'NUEVA ÁREA', new_admin_place_path, class: 'button' %>
      <span class="clear"></span>
    </div>
      
    <div class="table-cotainer">
        
      <table class="table table-hover dt-responsive nowrap">
        <thead>
          <tr>
            <th>Nombre</th>
            <th >Opciones</th>
          </tr>
        </thead>

        <tbody>
          <% @places.each do |place| %>
            <tr>

              <td>
                <%= place.name %>
              </td>

              <td>
                <%= link_to edit_admin_place_path(place), class: 'button button-icon' do %>
                    <i class="glyphicon glyphicon-pencil"></i>
                <% end %>
                <%= link_to admin_place_path(place), class: 'button button-icon', 
                    method: :delete, data: { confirm: '¿Estas seguro?' } do %>
                    <i class="glyphicon glyphicon-trash"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  
  </div>
</div>

app/views/admin/places/new.html.erb
<% content_for :title do %>
    Nueva Área
<% end %>

<div class="container-fluid">
    <div class="row">


        <div class="content-form col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">

            <h3 class="col-sm-12 page-title" >NUEVA ÁREA</h3>
            <%= render 'form', place: @place %>
        </div>
    </div>
</div>

app/views/admin/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<%= link_to 'Edit', edit_admin_place_path(@place) %> |
<%= link_to 'Back', places_path %>