config/routes.rb
Rails.application.routes.draw do
  
  get '', to: 'home#home', as: 'root'

  get 'unauthorized', to: 'home#unautorized'

  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    # registrations: 'users/registrations'
  }

  # namespace :user do
  #   root :to => "users#index"
  # end
  
  namespace :admin do
    # get 'users', to: 'users#index'
    # get 'users/new', to: 'users#new'
    # post 'users', to: 'users#create'
    # get 'users/:id', to: 'users#show', as: 'users_detail'
    resources :users
    resources :places
    resources :associateds

    get 'binnacle/list'
  end

  # resources :associated_place_referrals
  # resources :place_associateds
  resources :referrals
  resources :referreds
  # resources :associateds

  get ':id_referred/referrals', to: 'referrals#referrals_active', as: 'referrals_scanned'
  post ':id_referred/referrals', to: 'referrals#add_comment', as: 'referral_add_comment'
  # post 'add_comment', to: 'referrals#add_comment', as: 'referral_add_comment'
  get 'scan_qr', to: 'referrals#scan_qr', as: 'scan_referrals'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/associated.rb
class Associated < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :place_associateds, dependent: :destroy
  accepts_nested_attributes_for :user

  validates :user, presence: true
  validates :names, presence: true, length: { maximum: 40 }
  validates :surnames, presence: true, length: { maximum: 40 }
  validates :no_casa, presence: true, numericality: { only_integer: true }
  validates :identification_card, presence: true, uniqueness: true, numericality: { only_integer: true }
  validates :address, presence: true, length: { maximum: 100 }


  def full_name
    return names + ' ' + surnames
  end

end

app/controllers/admin/associateds_controller.rb
class Admin::AssociatedsController < ApplicationController
  load_and_authorize_resource
  before_action :set_associated, only: [:show, :edit, :update, :destroy]

  # GET /associateds
  # GET /associateds.json
  def index
    @associateds = Associated.all
  end

  # GET /associateds/1
  # GET /associateds/1.json
  def show
  end

  # GET /associateds/new
  def new
    @associated = Associated.new
    @associated.build_user
    get_places

    @error_places = ''

  end

  # GET /associateds/1/edit
  def edit
    get_places
    
    @error_places = ''
  end

  # POST /associateds
  # POST /associateds.json
  def create
    @associated = Associated.new(associated_params)
    @associated.user.is_associated = true

    @error_places = ''
    
    @associated.valid?

    @places_selected = params[:places]
    if !@places_selected
      @error_places = 'Debe selecionar al menos 1 area'
      get_places
      render :new
      return
    end

    respond_to do |format|
      if @associated.save
        
        areas = ''
        @places_selected.each do |p_id|
          @associated.place_associateds.create(place_id:p_id)
          areas = areas + Place.find(p_id).name + ','
        end

        Binnacle.create_binnacle('Crear asociado', current_user, @associated.full_name, 
          @associated.user.email, nil, nil, nil, nil, areas)

        format.html { redirect_to admin_associateds_url(@associated), notice: 'Asociado fue creado con éxito.' }
        format.json { render :show, status: :created, location: @associated }
      else
        get_places
        format.html { render :new }
        format.json { render json: @associated.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /associateds/1
  # PATCH/PUT /associateds/1.json
  def update
    @error_places = ''
    
    @associated.valid?

    @places_selected = params[:places]
    if !@places_selected
      @error_places = 'Debe selecionar al menos 1 area'
      get_places
      render :edit
      return
    end
    


    respond_to do |format|
      if @associated.update(associated_params)
        
        areas = ''
        @places_selected.each do |p_id|
          if !@associated.place_associateds.exists?(place_id:p_id)
            @associated.place_associateds.create(place_id:p_id)
          end
          
          areas = areas + Place.find(p_id).name.to_s + ','
        end
        
        Binnacle.create_binnacle('Editar asociado', current_user, @associated.full_name, 
          @associated.user.email, nil, nil, nil, nil, areas)
        
        
        @associated.place_associateds.each do |p|  
          begin
            p.destroy if !@places_selected.include? p.place_id.to_s
          rescue
            @error_places = 'El area "'+p.place.name + '" tiene un referimiento asignado, no puede ser borrada'
            get_places
            render :edit
            return
          end
        end


        format.html { redirect_to admin_associateds_url(@associated), notice: 'Asociado se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @associated }
      else
        get_places
        format.html { render :edit }
        format.json { render json: @associated.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /associateds/1
  # DELETE /associateds/1.json
  def destroy
    begin
      asso_name = @associated.full_name
      asso_email = @associated.user.email
      @associated.destroy
      respond_to do |format|

        Binnacle.create_binnacle('Borrar asociado', current_user, asso_name, 
          asso_email, nil, nil, nil, nil, nil)
        
          format.html { redirect_to admin_associateds_url, notice: 'Asociado fue destruido con éxito.' }
        format.json { head :no_content }
      end      
    rescue ActiveRecord::InvalidForeignKey 
      msg = 'El asociado "'+@associated.identification_card.to_s+'" tiene referimientos o referidos creados, no puede ser eliminado.'
      # flash.now[:notice] 
      respond_to do |format|
        format.html { redirect_to admin_associateds_url, alert: msg }
      end
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_associated
      @associated = Associated.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def associated_params
      params.require(:associated).permit(
        :names, :surnames, :identification_card, :no_casa, :address,
        user_attributes: [:email, :password]
      )
      
    end

    def get_places
      @places = Place.all
      @places_assigned = @associated.place_associateds
    end
end

app/controllers/associateds_controller.rb
class AssociatedsController < ApplicationController
  load_and_authorize_resource
  before_action :set_associated, only: [:show, :edit, :update, :destroy]

  # GET /associateds
  # GET /associateds.json
  def index
    @associateds = Associated.all
  end

  # GET /associateds/1
  # GET /associateds/1.json
  def show
  end

  # GET /associateds/new
  def new
    @associated = Associated.new
  end

  # GET /associateds/1/edit
  def edit
  end

  # POST /associateds
  # POST /associateds.json
  def create
    @associated = Associated.new(associated_params)

    respond_to do |format|
      if @associated.save
        format.html { redirect_to @associated, notice: 'Asociado fue creado con éxito.' }
        format.json { render :show, status: :created, location: @associated }
      else
        format.html { render :new }
        format.json { render json: @associated.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /associateds/1
  # PATCH/PUT /associateds/1.json
  def update
    respond_to do |format|
      if @associated.update(associated_params)
        format.html { redirect_to @associated, notice: 'Asociado se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @associated }
      else
        format.html { render :edit }
        format.json { render json: @associated.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /associateds/1
  # DELETE /associateds/1.json
  def destroy
    @associated.destroy
    respond_to do |format|
      format.html { redirect_to associateds_url, notice: 'Asociado fue destruido con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_associated
      @associated = Associated.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def associated_params
      params.require(:associated).permit(:names, :surnames, :id, :no_casa, :address, :user_id)
    end
end

app/helpers/associateds_helper.rb
module AssociatedsHelper
end

app/views/admin/associateds/_form.html.erb
	
<%= simple_form_for([:admin, associated], html: {multipart: true}, :defaults => { :input_html => { :class => "form-control" } }) do |f| %>
  
  <%= render  :partial=>"shared/display_errors", :locals => {:resource => @associated, :field => @error_places} %>


  <div class="form-group col-sm-12 <%= "has-error" if @associated.errors[:names].any? %>">
    <%= f.label :names, class: 'control-label' %>
    <%= f.input_field :names, class: 'form-control' %>
    <%= f.error :names, class:'help-block' %>
  </div>

  <div class="form-group col-sm-12 <%= "has-error" if @associated.errors[:surnames].any? %>">
    <%= f.label :surnames, class: 'control-label'  %>
    <%= f.input_field :surnames, class: 'form-control' %>
    <%= f.error :surnames, class:'help-block' %>
  </div>

  <div class="form-group col-sm-12 <%= "has-error" if @associated.errors[:identification_card].any? %>">
    <%= f.label :identification_card, class: 'control-label' %>
    <%= f.input_field :identification_card, class: 'form-control' %>
    <%= f.error :identification_card, class:'help-block' %>
  </div>

  <div class="form-group col-sm-12 <%= "has-error" if @associated.errors[:no_casa].any? %>">
    <%= f.label :no_casa, class: 'control-label' %>
    <%= f.input_field :no_casa, class: 'form-control' %>
    <%= f.error :no_casa, class:'help-block' %>
  </div>

  <div class="form-group col-sm-12 <%= "has-error" if @associated.errors[:address].any? %>">
    <%= f.label 'address', class: 'control-label' %>
    <%= f.input_field :address, class: 'form-control' %>
    <%= f.error :address, class:'help-block' %>
  </div>



  <div class="form-group col-sm-12 <%= "has-error" if @error_places != '' %>">
    <%= f.label 'places', class: 'control-label' do %>
      <abbr title="requerido">*</abbr>
      Área
    <% end %>
    <select class="form-control" multiple name="places[]" id="places">
      
      <option value="">Selecionar</option>
      
      <% @places.each do |place| %>
        <option value="<%= place.id %>"  ><%= place.name %></option>
      <% end %>
    </select>

    <span class="error help-block" > <%= raw @error_places %> </span>
    
  </div>




    <%= f.fields_for :user  do |form_user| %>
      <div class="form-group col-sm-12 <%= "has-error" if @associated.errors[:'user.email'].any? %>">
        <label for="associated_user_attributes_email" class="control-label">
          <abbr title="requerido">*</abbr>
          Email
        </label>
  
        <%= form_user.input_field :email, class: 'form-control' %>
        <%= f.error :'user.email', class:'help-block' %>
      </div>

      <div class="form-group col-sm-12 <%= "has-error" if @associated.errors[:'user.password'].any? %>">
        <label for="associated_user_attributes_password" class="control-label">
          <abbr title="requerido">*</abbr> Contraseña
        </label>
  
        <%= form_user.input_field :password, class: 'form-control' %>
        <%= f.error :'user.password', class:'help-block' %>
      </div>
    <% end %>
  



	<div class="form-group col-sm-12 " style="margin-bottom: 4px;" >
		
		<%= f.submit 'Guardar', :class => 'btn btn-primary  right' %>
		
		<%= link_to 'Atrás', admin_associateds_path %>
			
	</div>


<% end %>

app/views/admin/associateds/edit.html.erb
<% content_for :title do %>
    Editar Asociado
<% end %>

<div class="container-fluid">
  <div class="row">

    <div class="content-form col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">

      <h3 class="col-xs-12 page-title" >EDITAR ASOCIADO</h3>
                  
      <%= simple_form_for([:admin, @associated], html: {multipart: true}, :defaults => { :input_html => { :class => "form-control" } }) do |f| %>
        
        <%= render  :partial=>"shared/display_errors", :locals => {:resource => @associated, :field => @error_places} %>


        <div class="form-group col-sm-12 <%= "has-error" if @associated.errors[:names].any? %>">
          <%= f.label :names, class: 'control-label' %>
          <%= f.input_field :names, class: 'form-control' %>
          <%= f.error :names, class:'help-block' %>
        </div>

        <div class="form-group col-sm-12 <%= "has-error" if @associated.errors[:surnames].any? %>">
          <%= f.label :surnames, class: 'control-label'  %>
          <%= f.input_field :surnames, class: 'form-control' %>
          <%= f.error :surnames, class:'help-block' %>
        </div>

        <div class="form-group col-sm-12 <%= "has-error" if @associated.errors[:identification_card].any? %>">
          <%= f.label :identification_card, class: 'control-label' %>
          <%= f.input_field :identification_card, class: 'form-control' %>
          <%= f.error :identification_card, class:'help-block' %>
        </div>

        <div class="form-group col-sm-12 <%= "has-error" if @associated.errors[:no_casa].any? %>">
          <%= f.label :no_casa, class: 'control-label' %>
          <%= f.input_field :no_casa, class: 'form-control' %>
          <%= f.error :no_casa, class:'help-block' %>
        </div>

        <div class="form-group col-sm-12 <%= "has-error" if @associated.errors[:address].any? %>">
          <%= f.label 'address', class: 'control-label' %>
          <%= f.input_field :address, class: 'form-control' %>
          <%= f.error :address, class:'help-block' %>
        </div>



        <div class="form-group col-sm-12 <%= "has-error" if @error_places != '' %>" >
          <%= f.label 'places', class: 'control-label' %>

          <%= select_tag 'places[]', 
              options_for_select(Place.all.map { |p| [p.name, p.id] }, 
              @associated.place_associateds.pluck(:place_id)), 
              multiple: true,
              class: 'form-control'
          %>


          <span class="error help-block" > <%= raw @error_places %> </span>
          
        </div>


        <div class="form-group col-sm-12 " style="margin-bottom: 4px;" >
          
          <%= f.submit 'Guardar', :class => 'btn btn-primary  right' %>
          
          
        <%= link_to 'Atrás', admin_associateds_path %>
            
        </div>

      <% end %>
    </div>


  </div>

</div>

app/views/admin/associateds/index.html.erb
<% content_for :title do %>
    Asociados
<% end %>

<div class="container-fluid">
  <div class="row">

    <div class="content-index-title">
      <h3 class ="index-title"></h3>
      <%= link_to 'NUEVO ASOCIADO', new_admin_associated_path, class: 'button' %>
      <span class="clear"></span>
    </div>

    <div class="table-cotainer">
        
      <table class="table table-hover dt-responsive nowrap">
        <thead>
          <tr>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Cédula</th>
            <th>No. casa</th>
            <th>Dirección</th>
            <th>Correo</th>
            <th>Opciones</th>
          </tr>
        </thead>

        <tbody>
          <% @associateds.each do |associated| %>
            <tr>
              <td><%= associated.names %></td>
              <td><%= associated.surnames %></td>
              <td><%= associated.identification_card %></td>
              <td><%= associated.no_casa %></td>
              <td><%= associated.address %></td>
              <td><%= link_to associated.user.email, edit_admin_associated_path(associated) %></td>
              <td>
                <%= link_to edit_admin_associated_path(associated), class: 'button button-icon' do %>
                    <i class="glyphicon glyphicon-pencil"></i>
                <% end %>
                
                <%= link_to admin_associated_path(associated), class: 'button button-icon', 
                    method: :delete, data: { confirm: '¿Estas seguro?' } do %>
                    <i class="glyphicon glyphicon-trash"></i>
                <% end %>
              </td>
            
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/associateds/new.html.erb
<% content_for :title do %>
    Nuevo Asociado
<% end %>


<div class="container-fluid">
    <div class="row">


        <div class="content-form col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
            <h3 class="col-sm-12 page-title" >NUEVO ASOCIADO</h3>
            <%= render 'form', associated: @associated %>
        </div>
    </div>

</div>

app/views/admin/associateds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Names:</strong>
  <%= @associated.names %>
</p>

<p>
  <strong>Surnames:</strong>
  <%= @associated.surnames %>
</p>

<p>
  <strong>Id:</strong>
  <%= @associated.id %>
</p>

<p>
  <strong>No casa:</strong>
  <%= @associated.no_casa %>
</p>

<p>
  <strong>Address:</strong>
  <%= @associated.address %>
</p>

<p>
  <strong>User:</strong>
  <%= @associated.user %>
</p>

<%= link_to 'Edit', edit_associated_path(@associated) %> |
<%= link_to 'Back', associateds_path %>