config/routes.rb
Rails.application.routes.draw do
  
  get '', to: 'home#home', as: 'root'

  get 'unauthorized', to: 'home#unautorized'

  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    # registrations: 'users/registrations'
  }

  # namespace :user do
  #   root :to => "users#index"
  # end
  
  namespace :admin do
    # get 'users', to: 'users#index'
    # get 'users/new', to: 'users#new'
    # post 'users', to: 'users#create'
    # get 'users/:id', to: 'users#show', as: 'users_detail'
    resources :users
    resources :places
    resources :associateds

    get 'binnacle/list'
  end

  # resources :associated_place_referrals
  # resources :place_associateds
  resources :referrals
  resources :referreds
  # resources :associateds

  get ':id_referred/referrals', to: 'referrals#referrals_active', as: 'referrals_scanned'
  post ':id_referred/referrals', to: 'referrals#add_comment', as: 'referral_add_comment'
  # post 'add_comment', to: 'referrals#add_comment', as: 'referral_add_comment'
  get 'scan_qr', to: 'referrals#scan_qr', as: 'scan_referrals'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li>
    <%= link_to edit_user_registration_path, 
        class: is_active?(edit_user_registration_path),
        "data-toggle" => "tooltip", 
        "title" => "Cambiar contraseña" do %>
      <i class="glyphicon glyphicon-lock"></i>
    <% end %>
  </li>

  <li>
    <%= link_to destroy_user_session_path , :method=>'delete',
        "data-toggle" => "tooltip", 
        "title" => "Cerrar sesión"  do %>
      <i class="glyphicon glyphicon-log-out" ></i>
    <% end %>
  </li>
  
<% else %>

  <li>

    <%= link_to new_user_session_path, 
        "data-toggle" => "tooltip", 
        "title" => "Iniciar sesión" do %>
      <i class="glyphicon glyphicon-log-in"></i>
    <% end %>  

  </li>
<% end %>
   

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default ">
  <div class="container-fluid">
    <div class="navbar-header navbar-left pull-left">
      <%= link_to 'users', class: 'navbar-brand' do %>
        <%= image_tag("siscotel-logo.png", :alt => "referimiento logo") %>
      <% end %>

    </div>

    <div class="navbar-header pull-left">
      <ul class="nav navbar-nav navbar-left" >
        <li>
          <p class="title-navbar navbar-text"><%= content_for?(:title) ? yield(:title) : "Referimiento" %></p>
        </li>
      </ul>
    </div>

      
    <div class="navbar-header navbar-right pull-right">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>

  </div>
</nav>

<% if user_signed_in? %>
<nav class="navbar navbar-inverse nav" id="navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-left">
        <%= render 'layouts/navigation_links' %>
      </ul>

    </div>
  </div>
</nav>
<% end %>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>

    <% if current_user.is_admin? %>
        <li><%= link_to  "USUARIOS", admin_users_path, class: is_active?(admin_users_path) %></li>
        <li><%= link_to  "ASOCIADOS", admin_associateds_path, class: is_active?(admin_associateds_path) %></li>
        <li><%= link_to  "LUGARES", admin_places_path, class: is_active?(admin_places_path) %></li>
        <li><%= link_to  "BITÁCORA", admin_binnacle_list_path, class: is_active?(admin_binnacle_list_path) %></li>
    <% elsif current_user.is_vigilant? %>
        <li><%= link_to  "SCANEAR QR", scan_referrals_path, class: is_active?(scan_referrals_path) %></li>
    <% elsif current_user.is_associated? %>
        <li><%= link_to  "REFERIDOS", referreds_path, class: is_active?(referreds_path) %></li>
        <li><%= link_to  "REFERIMIENTOS", referrals_path, class: is_active?(referrals_path) %></li>
    <%end%>

<%end%>

   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Referimiento</title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Referimiento" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Referimiento" %>">
    


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# <script type="text/javascript" src="https://cdn.datatables.net/v/bs/jq-3.3.1/dt-1.10.20/r-2.2.3/datatables.min.js"></script> %>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.20/r-2.2.3/datatables.min.js"></script>

    <script>

      const datatable_lan = {
          "sProcessing":     "Procesando...",
          "sLengthMenu":     "Mostrar _MENU_ registros",
          "sZeroRecords":    "No se encontraron resultados",
          "sEmptyTable":     "Ningún dato disponible en esta tabla =(",
          "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
          "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
          "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
          "sInfoPostFix":    "",
          "sSearch":         "Buscar:",
          "sUrl":            "",
          "sInfoThousands":  ",",
          "sLoadingRecords": "Cargando...",
          "oPaginate": {
              "sFirst":    "Primero",
              "sLast":     "Último",
              "sNext":     "Siguiente",
              "sPrevious": "Anterior"
          },
          "oAria": {
              "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
              "sSortDescending": ": Activar para ordenar la columna de manera descendente"
          },
          "buttons": {
              "copy": "Copiar",
              "colvis": "Visibilidad"
          }
      }

    </script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jq-3.3.1/dt-1.10.20/r-2.2.3/datatables.min.css"/> %>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.20/r-2.2.3/datatables.min.css"/>
 

    <%= csrf_meta_tags %>

    <link rel="manifest" href="/manifest.json" />
    <meta name="apple-mobile-web-app-capable" content="yes">
  </head>

  <body>



    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>

   
   
    
    <script>

      $(document).ready( function () {
        setTimeout(function() {
          $('.alert.alert-dismissible').slideUp();
        }, 3000);

        window.onscroll = function() {myFunction()};

        // Get the navbar
        var navbar = document.getElementById("navbar");

        // Get the offset position of the navbar
        var sticky = navbar.offsetTop;

        // Add the sticky class to the navbar when you reach its scroll position. Remove "sticky" when you leave the scroll position
        
        function myFunction() {
            if (window.pageYOffset >= sticky) {
              navbar.classList.add("sticky")
            } else {
              navbar.classList.remove("sticky");
            }
        }
        
        // try {

         
          var table = $('table').DataTable({
            "language": datatable_lan
          }); 


          $( '.filters-table input,.filters-table .input').on( 'keyup change',function () {
            console.log(this.value, $(this).data('index'))

            table
            .column( parseInt($(this).data('index')) )
            .search( this.value )
            .draw();
          } );
        // } catch (error) {
          
        // }
      })
    </script>


    
    <%= yield :js %>

  </body>
</html>